export const UPDATE_USER_NAME  = 'UPDATE_USER_NAME';
export const UPDATE_USER_PHOTO = 'UPDATE_USER_PHOTO';
export const UPDATE_USER_COVER = 'UPDATE_USER_COVER';

export const API = 'API';
export const API_SUCCESS = 'API_SUCCESS';
export const API_FAILURE = 'API_FAILURE';

export const UPDATE_TWEET_LIST = 'UPDATE_TWEET_LIST'